CREATE TABLE [tbl_Personnel_Master] (
  [PersonUID] VARCHAR (50) CONSTRAINT [idx_PersonUID] UNIQUE CONSTRAINT [PK_Person] PRIMARY KEY UNIQUE NOT NULL,
  [SourceID] LONG,
  [FullName] VARCHAR (150),
  [RankName] VARCHAR (100),
  [WorkStatus] VARCHAR (100),
  [PosCode] VARCHAR (50),
  [PosName] LONGTEXT,
  [LastUpdated] DATETIME,
  [IsActive] BIT,
  [BirthDate_Text] VARCHAR (255),
  [EmployeeAge] VARCHAR (255),
  [Gender] VARCHAR (255),
  [MaritalStatus] VARCHAR (255),
  [ChildrenCount] VARCHAR (255),
  [Nationality] VARCHAR (255),
  [Citizenship] VARCHAR (255),
  [ContractType] VARCHAR (255),
  [ContractKind] VARCHAR (255),
  [ContractStartDate] VARCHAR (255),
  [ContractEndDate] VARCHAR (255),
  [ContractYears] LONG,
  [ContractMonths] LONG,
  [OrderNumber] VARCHAR (255),
  [OrderDate_Text] VARCHAR (255),
  [EventType] VARCHAR (255),
  [EventReason] VARCHAR (255),
  [ValidFromDate] VARCHAR (255),
  [ValidToDate] VARCHAR (255),
  [StaffPosition] VARCHAR (255),
  [Position] VARCHAR (255),
  [VUS] VARCHAR (255),
  [SalaryGrade] VARCHAR (255),
  [PersonnelDivision] VARCHAR (255),
  [BankAccountNumber] VARCHAR (255),
  [Payee] VARCHAR (255),
  [BankKey] VARCHAR (255),
  [BootSize] VARCHAR (255),
  [HeadSize] VARCHAR (255),
  [Address] LONGTEXT
)
