CREATE TABLE [tbl_Import_Buffer] (
  [ID] AUTOINCREMENT CONSTRAINT [PK_Buffer] PRIMARY KEY UNIQUE NOT NULL,
  [EmployeeAge] VARCHAR (255),
  [Gender] VARCHAR (255),
  [BirthDate_Text] VARCHAR (255),
  [MaritalStatus] VARCHAR (255),
  [ChildrenCount] VARCHAR (255),
  [Nationality] VARCHAR (255),
  [Citizenship] VARCHAR (255),
  [ContractType] VARCHAR (255),
  [ContractKind] VARCHAR (255),
  [ContractStartDate] VARCHAR (255),
  [ContractEndDate] VARCHAR (255),
  [ContractYears] LONG,
  [ContractMonths] LONG,
  [OrderNumber] VARCHAR (255),
  [OrderDate_Text] VARCHAR (255),
  [EventType] VARCHAR (255),
  [EventReason] VARCHAR (255),
  [ValidFromDate] VARCHAR (255),
  [ValidToDate] VARCHAR (255),
  [StaffPosition] VARCHAR (255),
  [Position] VARCHAR (255),
  [VUS] VARCHAR (255),
  [SalaryGrade] VARCHAR (255),
  [PersonnelDivision] VARCHAR (255),
  [BankAccountNumber] VARCHAR (255),
  [Payee] VARCHAR (255),
  [BankKey] VARCHAR (255),
  [BootSize] VARCHAR (255),
  [HeadSize] VARCHAR (255),
  [DismissalDate] VARCHAR (255),
  [EmployeeGroup] VARCHAR (255),
  [CalculationUnit] VARCHAR (255),
  [CalculatedBy] VARCHAR (255),
  [StaffPosition1] VARCHAR (255),
  [OrderDate_LS] VARCHAR (255),
  [OrderNumber1] VARCHAR (255),
  [PositionOrderIssuer] VARCHAR (255),
  [PersonnelDivision1] VARCHAR (255),
  [EmploymentStatus] VARCHAR (255),
  [BankControlKey] VARCHAR (255),
  [PersonUID] VARCHAR (255),
  [FullName] VARCHAR (255),
  [SourceID] VARCHAR (255),
  [RankName] VARCHAR (255),
  [BirthDate] VARCHAR (255),
  [Address] LONGTEXT
)
