CREATE TABLE [tbl_Personnel_Master] (
  [PersonUID] VARCHAR (50) CONSTRAINT [idx_PersonUID] UNIQUE CONSTRAINT [PK_Person] PRIMARY KEY UNIQUE NOT NULL,
  [SourceID] LONG,
  [FullName] VARCHAR (150),
  [RankName] VARCHAR (100),
  [BirthDate] DATETIME,
  [WorkStatus] VARCHAR (100),
  [PosCode] VARCHAR (50),
  [PosName] LONGTEXT,
  [OrderDate] DATETIME,
  [OrderNum] VARCHAR (50),
  [LastUpdated] DATETIME,
  [IsActive] BIT,
  [ID] VARCHAR (255),
  [SourceID_Raw] VARCHAR (255),
  [PersonUID_Raw] VARCHAR (255),
  [Rank_Raw] VARCHAR (255),
  [FullName_Raw] VARCHAR (255),
  [BirthDate_Raw] VARCHAR (255),
  [WorkStatus_Raw] VARCHAR (255),
  [PosCode_Raw] VARCHAR (255),
  [PosName_Raw] VARCHAR (255),
  [OrderDate_Raw] VARCHAR (255),
  [OrderNum_Raw] VARCHAR (255),
  [Дата_рождения] VARCHAR (255),
  [Возраст_сотрудника] VARCHAR (255),
  [Пол] VARCHAR (255),
  [Семейное_положение] VARCHAR (255),
  [Количество_детей] VARCHAR (255),
  [Национальность] VARCHAR (255),
  [Гражданство] VARCHAR (255),
  [Дата_увольнения] VARCHAR (255),
  [Группа_сотрудников] VARCHAR (255),
  [Вид_контракта] VARCHAR (255),
  [Тип_контракта] VARCHAR (255),
  [Дата_начала_контракта] VARCHAR (255),
  [Дата_окончания_контракта] VARCHAR (255),
  [Срок_договора_год] VARCHAR (255),
  [Срок_договора_месяц] VARCHAR (255),
  [Номер_приказа] VARCHAR (255),
  [Дата_приказа] VARCHAR (255),
  [Вид_мероприятия] VARCHAR (255),
  [Причина_мероприятия] VARCHAR (255),
  [Начало_срока_действия] VARCHAR (255),
  [Конец_срока_действия] VARCHAR (255),
  [Штатная_должность] VARCHAR (255),
  [Должность] VARCHAR (255),
  [Единица_расчета] VARCHAR (255),
  [Рассчитано_по] VARCHAR (255),
  [Штатная_должность1] VARCHAR (255),
  [ВУС] VARCHAR (255),
  [Тарифный_разряд] VARCHAR (255),
  [Дата_приказа_Л_С] VARCHAR (255),
  [Номер_приказа1] VARCHAR (255),
  [Чей_приказ_должность] VARCHAR (255),
  [Раздел_персонала] VARCHAR (255),
  [Раздел_персонала1] VARCHAR (255),
  [Статус_занятости] VARCHAR (255),
  [Контрольный_банковский_ключ] VARCHAR (255),
  [Номер_счета_в_банке] VARCHAR (255),
  [Получатель] VARCHAR (255),
  [Ключ_банка] VARCHAR (255),
  [Размер_Сапог] VARCHAR (255),
  [F44] VARCHAR (255),
  [Охват_головы] VARCHAR (255),
  [PosCode_Raw_2] VARCHAR (255),
  [OrderDate_Raw_2] VARCHAR (255),
  [OrderNum_Raw_2] VARCHAR (255),
  [PosName_Raw_2] VARCHAR (255)
)
